### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [veltzer/pyscrapers#4]
Is it possible to get post information, from a public page such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

without login?

**Comment by veltzer** [comment]
It looks like it is possible. Just log out and verity that you can see the page.

**Comment by veltzer** [comment]
But why did you post this as an issue on pyscrapers? This is general question that has nothing to do with pyscrapers. It is certainly not an issue with pyscrapers.... I'm closing this....

**Comment by 89z** [comment]
It says this in the about section:

> Scrapers for vk, facebook, instagram and more 

on this page:

https://github.com/veltzer/pyscrapers

**Comment by veltzer** [comment]
Sure but it doesn't do posts for now...And the question is about the possibility of doing it, not abut pyscrapers implementation... General question about you can and can't do don't belong in software issue of pyscrapers... This is not a general discussion forum. I expect only bugs here...

**Comment by 89z** [comment]
OK, so where is the general discussion forum?

**Comment by veltzer** [comment]
I do not have a forum...:) This is still a young project. You can reopen this as a "feature request" feature...
